#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE "${GRAFANA_USER}" WITH LOGIN PASSWORD '${GRAFANA_PASSWORD}';

    GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${GRAFANA_USER}";
    GRANT USAGE ON SCHEMA public TO "${GRAFANA_USER}";

    GRANT SELECT ON ALL TABLES IN SCHEMA public TO "${GRAFANA_USER}";

    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT SELECT ON TABLES TO "${GRAFANA_USER}";
EOSQL